### ISSUE TITLE
Do we need to add JIRA automation (changes.md gen) and track Fix Versions

### ISSUE THREAD

**Issue by mrutkows** [apache/openwhisk-release#179]
Please read what Apache Beam does with JIRA here:
https://beam.apache.org/contribute/release-guide/

**Comment by mrutkows** [comment]
If we can minimize reliance on JIRA the better since most Contributors and Committers on our project are new to Apache and rely solely on Git(Hub) and do not want to force a JIRA process on-top of a process we have working now in GitHub.  Do we need to document this before we release?

**Comment by houshengbo** [comment]
@mrutkows So far, we can stay with our process as documented in the instruction of openwhisk release. Our instruction for the release manager is informative enough for us to follow in order to release. We can opened an issue in JIRA called "Calling for release of OpenWhisk", listing all the artifacts we release and make the community aware of that we are in the process of the release, and ask them to read the email, test and vote.
